//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleWareReports {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Convertions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Convertions() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiddleWareReports.utils.Convertions", typeof(Convertions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string activeTime {
            get {
                return ResourceManager.GetString("activeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string AverageHandleTime {
            get {
                return ResourceManager.GetString("AverageHandleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avg {
            get {
                return ResourceManager.GetString("avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgAbandonTime {
            get {
                return ResourceManager.GetString("avgAbandonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgCallTime {
            get {
                return ResourceManager.GetString("avgCallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgTimeBetweenCalls {
            get {
                return ResourceManager.GetString("avgTimeBetweenCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgTQueueCalls {
            get {
                return ResourceManager.GetString("avgTQueueCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgTQueueChats {
            get {
                return ResourceManager.GetString("avgTQueueChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgWrapupTime {
            get {
                return ResourceManager.GetString("avgWrapupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avgXfer {
            get {
                return ResourceManager.GetString("avgXfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string avrAnswer {
            get {
                return ResourceManager.GetString("avrAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string crmx_duration {
            get {
                return ResourceManager.GetString("crmx_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string dialog {
            get {
                return ResourceManager.GetString("dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string dialogTime {
            get {
                return ResourceManager.GetString("dialogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string holdTime {
            get {
                return ResourceManager.GetString("holdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string loginMktTime {
            get {
                return ResourceManager.GetString("loginMktTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string logoutMktTime {
            get {
                return ResourceManager.GetString("logoutMktTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string maxDelay {
            get {
                return ResourceManager.GetString("maxDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string maxTQueueCalls {
            get {
                return ResourceManager.GetString("maxTQueueCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string maxTQueueChats {
            get {
                return ResourceManager.GetString("maxTQueueChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string MessageTime {
            get {
                return ResourceManager.GetString("MessageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string mohTime {
            get {
                return ResourceManager.GetString("mohTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdBreak {
            get {
                return ResourceManager.GetString("NdBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdCallWork {
            get {
                return ResourceManager.GetString("NdCallWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdCapacitacion {
            get {
                return ResourceManager.GetString("NdCapacitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdFalla {
            get {
                return ResourceManager.GetString("NdFalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdInicio {
            get {
                return ResourceManager.GetString("NdInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdPagos {
            get {
                return ResourceManager.GetString("NdPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdPausaGrl {
            get {
                return ResourceManager.GetString("NdPausaGrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdPersonal {
            get {
                return ResourceManager.GetString("NdPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdRetro {
            get {
                return ResourceManager.GetString("NdRetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdRH {
            get {
                return ResourceManager.GetString("NdRH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string ndTime {
            get {
                return ResourceManager.GetString("ndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string NdTrabajoAdm {
            get {
                return ResourceManager.GetString("NdTrabajoAdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string nminutes {
            get {
                return ResourceManager.GetString("nminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string notReadyTime {
            get {
                return ResourceManager.GetString("notReadyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string oHour {
            get {
                return ResourceManager.GetString("oHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string postime {
            get {
                return ResourceManager.GetString("postime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string PromDialog {
            get {
                return ResourceManager.GetString("PromDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string queueTime {
            get {
                return ResourceManager.GetString("queueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string readyTime {
            get {
                return ResourceManager.GetString("readyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string ringingTime {
            get {
                return ResourceManager.GetString("ringingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string sessionTime {
            get {
                return ResourceManager.GetString("sessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string statusTime {
            get {
                return ResourceManager.GetString("statusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tabndtot {
            get {
                return ResourceManager.GetString("tabndtot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tACD {
            get {
                return ResourceManager.GetString("tACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tACW {
            get {
                return ResourceManager.GetString("tACW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tAgent {
            get {
                return ResourceManager.GetString("tAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string talkingtTime {
            get {
                return ResourceManager.GetString("talkingtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tatencion {
            get {
                return ResourceManager.GetString("tatencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tatention {
            get {
                return ResourceManager.GetString("tatention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tAtentionMultimedia {
            get {
                return ResourceManager.GetString("tAtentionMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tAux {
            get {
                return ResourceManager.GetString("tAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tav {
            get {
                return ResourceManager.GetString("tav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tavg {
            get {
                return ResourceManager.GetString("tavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tAvgAtentionMultimedia {
            get {
                return ResourceManager.GetString("tAvgAtentionMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tBusy {
            get {
                return ResourceManager.GetString("tBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tCallTransf {
            get {
                return ResourceManager.GetString("tCallTransf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tChatting {
            get {
                return ResourceManager.GetString("tChatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tCliente {
            get {
                return ResourceManager.GetString("tCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tDescon {
            get {
                return ResourceManager.GetString("tDescon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tdialog {
            get {
                return ResourceManager.GetString("tdialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tdialogin {
            get {
                return ResourceManager.GetString("tdialogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tdialogout {
            get {
                return ResourceManager.GetString("tdialogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tfocus {
            get {
                return ResourceManager.GetString("tfocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoACW {
            get {
                return ResourceManager.GetString("TiempoACW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoDispo {
            get {
                return ResourceManager.GetString("TiempoDispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoLlamadoAgente {
            get {
                return ResourceManager.GetString("TiempoLlamadoAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoPromACD {
            get {
                return ResourceManager.GetString("TiempoPromACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoPromACW {
            get {
                return ResourceManager.GetString("TiempoPromACW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoPromReten {
            get {
                return ResourceManager.GetString("TiempoPromReten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoPromRing {
            get {
                return ResourceManager.GetString("TiempoPromRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TiempoSalidaExt {
            get {
                return ResourceManager.GetString("TiempoSalidaExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string timeafterxfer {
            get {
                return ResourceManager.GetString("timeafterxfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string timeansware {
            get {
                return ResourceManager.GetString("timeansware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string timebeforexfer {
            get {
                return ResourceManager.GetString("timebeforexfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string timeMessage {
            get {
                return ResourceManager.GetString("timeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string timeretention {
            get {
                return ResourceManager.GetString("timeretention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tlog {
            get {
                return ResourceManager.GetString("tlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tLogout {
            get {
                return ResourceManager.GetString("tLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tManual {
            get {
                return ResourceManager.GetString("tManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tnav {
            get {
                return ResourceManager.GetString("tnav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tnotav {
            get {
                return ResourceManager.GetString("tnotav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tnotavg {
            get {
                return ResourceManager.GetString("tnotavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tnotesin {
            get {
                return ResourceManager.GetString("tnotesin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tnotesout {
            get {
                return ResourceManager.GetString("tnotesout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string totalaTencion {
            get {
                return ResourceManager.GetString("totalaTencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string totalWait {
            get {
                return ResourceManager.GetString("totalWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tother {
            get {
                return ResourceManager.GetString("tother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tPer {
            get {
                return ResourceManager.GetString("tPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tprob {
            get {
                return ResourceManager.GetString("tprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tPromACD {
            get {
                return ResourceManager.GetString("tPromACD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tPromACW {
            get {
                return ResourceManager.GetString("tPromACW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TPromDispon {
            get {
                return ResourceManager.GetString("TPromDispon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tPromElimCola {
            get {
                return ResourceManager.GetString("tPromElimCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tPromRetention {
            get {
                return ResourceManager.GetString("tPromRetention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string TPromRing {
            get {
                return ResourceManager.GetString("TPromRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tPromSalidaExt {
            get {
                return ResourceManager.GetString("tPromSalidaExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tque {
            get {
                return ResourceManager.GetString("tque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tque_max {
            get {
                return ResourceManager.GetString("tque_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tque2 {
            get {
                return ResourceManager.GetString("tque2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tqueavg {
            get {
                return ResourceManager.GetString("tqueavg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tquemax {
            get {
                return ResourceManager.GetString("tquemax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tQueue {
            get {
                return ResourceManager.GetString("tQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tQueueMultimedia {
            get {
                return ResourceManager.GetString("tQueueMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string treq {
            get {
                return ResourceManager.GetString("treq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tresp {
            get {
                return ResourceManager.GetString("tresp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tResponse {
            get {
                return ResourceManager.GetString("tResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tResponseMail {
            get {
                return ResourceManager.GetString("tResponseMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tring {
            get {
                return ResourceManager.GetString("tring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tringin {
            get {
                return ResourceManager.GetString("tringin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tringout {
            get {
                return ResourceManager.GetString("tringout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tsend {
            get {
                return ResourceManager.GetString("tsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tundefined {
            get {
                return ResourceManager.GetString("tundefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tunknown {
            get {
                return ResourceManager.GetString("tunknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string tWait {
            get {
                return ResourceManager.GetString("tWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string twaitMultimedia {
            get {
                return ResourceManager.GetString("twaitMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string twbCall {
            get {
                return ResourceManager.GetString("twbCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string twrapup {
            get {
                return ResourceManager.GetString("twrapup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string txfer {
            get {
                return ResourceManager.GetString("txfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string txferin {
            get {
                return ResourceManager.GetString("txferin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string txferout {
            get {
                return ResourceManager.GetString("txferout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string unavaibleTime {
            get {
                return ResourceManager.GetString("unavaibleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string wrapup {
            get {
                return ResourceManager.GetString("wrapup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a convertToTime.
        /// </summary>
        public static string xferTime {
            get {
                return ResourceManager.GetString("xferTime", resourceCulture);
            }
        }
    }
}
