services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver2017
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Nuxiba2024_"
    ports:
      - "1436:1433"
    volumes:
      - ./Data:/var/opt/mssql/data
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge