# must be unique in a given SonarQube instance
sonar.projectKey=cw-database
sonar.projectName=cw-database
sonar.projectVersion=126.20240930.0.0
sonar.sources=schema-db/SaveSchemaDbServices/bin/Debug/SCHEMA_BD
sonar.language=tsql  # T-SQL para SQL Server
sonar.sourceEncoding=UTF-8