# must be unique in a given SonarQube instance
sonar.projectKey=cw-database
sonar.projectName=cw-database
sonar.projectVersion=126.20240930.0.0
sonar.sources=./CCenterRIA/UpdateDB,./ccReportsRia/UpdateDB,./RecorderRIA/UpdateDB  # Directorios donde están los scripts SQL
sonar.language=tsql  # T-SQL para SQL Server
sonar.sourceEncoding=UTF-8
