ALTER VIEW [dbo].[RepOutDialDetailView] AS   
SELECT  
    [date],  
    [callKey],  
    [telephone],  
    [dialResultId],  
    [dialResult],  
    [campaignId],  
    [campaign],  
    [timeMessage],  
    [year],  
    [month],  
    [day],  
    [hour],  
    [minutes],  
    [listName],  
    [billed],  
    [data1] AS [Dato1],  
    [data2] AS [Dato2],  
    [data3] AS [Dato3],  
    [data4] AS [Dato4],  
    [data5] AS [Dato5],  
    [fileMoved],  
    [DCCustomer],  
    [disconnectCause],  

    [dialType],  
    [ValidationMode],  

    [TipoTel],  
    [CallDisposition],  
    [CallSubDisposition],  
    [data6],  
    [data7],  
    [data8],  
    [data9],  
    [data10],  
    [data11],  
    [data12],  
    [data13],  
    [data14],  
    [data15],  
    [preview_Time],  
    [login] AS [user],  
    [areaId],  
    [area]  

FROM RepOutDialDetail WITH (NOLOCK);