CREATE VIEW RepViewAgentGISpecial AS
select date,
userId,
[user],
login,
tnotesout as tnotesoutNum,
tdialogout as tdialogoutxxx,
tringout as tringoutxxx,
txferout as txferoutxxx,
tunknown as tunknownxxx,
tother as totherxxx,
tprob as tprobxxx,
tundefined as tundefinedxxx,
tav as tavNum,
0.0 as tTalkNum,
tnotav as tnotavNum,
0.0 as TotalNum,
year,month,day,hour,minutes from RepAgentGI