//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiddleWareReports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiddleWareReports.language.detail.ResourcesDetail", typeof(ResourcesDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Campañana/Grupo ACD.
        /// </summary>
        public static string cam_id {
            get {
                return ResourceManager.GetString("cam_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaña/Grupo ACD.
        /// </summary>
        public static string campaignAcd {
            get {
                return ResourceManager.GetString("campaignAcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de chat.
        /// </summary>
        public static string chatId {
            get {
                return ResourceManager.GetString("chatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string dateStartDetail {
            get {
                return ResourceManager.GetString("dateStartDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string dateStartDetailin {
            get {
                return ResourceManager.GetString("dateStartDetailin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string dateStartDetailout {
            get {
                return ResourceManager.GetString("dateStartDetailout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación.
        /// </summary>
        public static string Disposisiton2 {
            get {
                return ResourceManager.GetString("Disposisiton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de conversación.
        /// </summary>
        public static string idMedia {
            get {
                return ResourceManager.GetString("idMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo ACD.
        /// </summary>
        public static string inbound {
            get {
                return ResourceManager.GetString("inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de Especialidad.
        /// </summary>
        public static string inboundId {
            get {
                return ResourceManager.GetString("inboundId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio.
        /// </summary>
        public static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono (Entrada).
        /// </summary>
        public static string phonein {
            get {
                return ResourceManager.GetString("phonein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono (Salida).
        /// </summary>
        public static string phoneout {
            get {
                return ResourceManager.GetString("phoneout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de llamada.
        /// </summary>
        public static string tipoLlamada {
            get {
                return ResourceManager.GetString("tipoLlamada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de Agente.
        /// </summary>
        public static string userId {
            get {
                return ResourceManager.GetString("userId", resourceCulture);
            }
        }
    }
}
