CREATE PROCEDURE [dbo].[trsp_GetNetworkCredentials]
@id integer = 0,
@domain nvarchar(50) = '',
@type integer = 0
AS
BEGIN

DECLARE @SQL as nvarchar(MAX)
DECLARE @isXION as integer

--Get AVRS enviroment
SET @isXION = (SELECT par_valor FROM  TREC_PARAMETROS WHERE par_id = 29)

IF @isXION = 2
BEGIN

IF @id <> 0 and @type <> 0 BEGIN

	--Get network credential for id
	SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],RIA_NETWORKCREDENTIALS.[user], RIA_NETWORKCREDENTIALS.[domain],RIA_NETWORKCREDENTIALS.[password], RIA_NETWORKCREDENTIALS.[id] AS id_credential
FROM RIA_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON RIA_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE RIA_NETWORKCREDENTIALS.[id] = ' +	CONVERT(varchar(20), @id) + ' AND RIA_NETWORKCREDENTIALS.[type] = '+ CONVERT(varchar(20), @TYPE) + ' AND RIA_NETWORKCREDENTIALS.[status]=1'

END
ELSE IF LEN(@domain) > 0 and @type <> 0 BEGIN

	--Get network credential for domail
	SET @SQL = 'SELECT top 1 TREC_REPO_NWCREDENTIALS.[id_repository],RIA_NETWORKCREDENTIALS.[user], RIA_NETWORKCREDENTIALS.[domain],RIA_NETWORKCREDENTIALS.[password], RIA_NETWORKCREDENTIALS.[id] AS id_credential
FROM RIA_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON RIA_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE RIA_NETWORKCREDENTIALS.domain = ''' + @domain + '''' + ' AND RIA_NETWORKCREDENTIALS.[type] = '+ CONVERT(varchar(20), @TYPE) +'AND RIA_NETWORKCREDENTIALS.[status]=1'

END
ELSE IF @type <> 0 and @id = 0 and LEN(@domain) = 0 BEGIN
	--Get network credential for domail
	SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],RIA_NETWORKCREDENTIALS.[user], RIA_NETWORKCREDENTIALS.[domain],RIA_NETWORKCREDENTIALS.[password], RIA_NETWORKCREDENTIALS.[id] AS id_credential
FROM RIA_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON RIA_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE RIA_NETWORKCREDENTIALS.[type] = '+ CONVERT(varchar(20), @TYPE) +'AND RIA_NETWORKCREDENTIALS.[status]=1'

END
ELSE  BEGIN

	--Get all network credentials
	SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],RIA_NETWORKCREDENTIALS.[user], RIA_NETWORKCREDENTIALS.[domain],RIA_NETWORKCREDENTIALS.[password], RIA_NETWORKCREDENTIALS.[id] AS id_credential
FROM RIA_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON RIA_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE RIA_NETWORKCREDENTIALS.[status]=1'

END

END
ELSE
BEGIN

IF @id <> 0 and @type <> 0
BEGIN

--Get network credential for id
SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],TREC_NETWORKCREDENTIALS.[user], TREC_NETWORKCREDENTIALS.[domain],TREC_NETWORKCREDENTIALS.[password], TREC_NETWORKCREDENTIALS.[id] AS id_credential
FROM TREC_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON TREC_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE TREC_NETWORKCREDENTIALS.[id] = ' +	CONVERT(varchar(20), @id) + ' AND TREC_NETWORKCREDENTIALS.[type] = ''+ CONVERT(varchar(20), @TYPE) + '' AND TREC_NETWORKCREDENTIALS.[status]=1'

END
ELSE IF LEN(@domain) > 0 and @type <> 0
BEGIN

--Get network credential for domain
SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],TREC_NETWORKCREDENTIALS.[user], TREC_NETWORKCREDENTIALS.[domain],TREC_NETWORKCREDENTIALS.[password], TREC_NETWORKCREDENTIALS.[id] AS id_credential
FROM TREC_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON TREC_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE TREC_NETWORKCREDENTIALS.domain = ''' + @domain + '''' + ' AND TREC_NETWORKCREDENTIALS.[type] = ''+ CONVERT(varchar(20), @TYPE) +''AND TREC_NETWORKCREDENTIALSe.[status]=1'

END
ELSE IF @type <> 0 and @id = 0 and LEN(@domain) = 0
BEGIN
--Get network credential for type
SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],TREC_NETWORKCREDENTIALS.[user], TREC_NETWORKCREDENTIALS.[domain],TREC_NETWORKCREDENTIALS.[password], TREC_NETWORKCREDENTIALS.[id] AS id_credential
FROM TREC_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON TREC_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE TREC_NETWORKCREDENTIALS.[type] = '+ CONVERT(varchar(20), @TYPE) +'AND TREC_NETWORKCREDENTIALSe.[status]=1'

END
ELSE
BEGIN

--Get all network credentials
SET @SQL = 'SELECT TREC_REPO_NWCREDENTIALS.[id_repository],TREC_NETWORKCREDENTIALS.[user], TREC_NETWORKCREDENTIALS.[domain],TREC_NETWORKCREDENTIALS.[password], TREC_NETWORKCREDENTIALS.[id] AS id_credential
FROM TREC_NETWORKCREDENTIALS
JOIN TREC_REPO_NWCREDENTIALS
ON TREC_NETWORKCREDENTIALS.id=TREC_REPO_NWCREDENTIALS.[id_nwCredential]
WHERE TREC_NETWORKCREDENTIALS.[status]=1'

END

END

	EXEC SP_EXECUTESQL @SQL

END